### ISSUE TITLE
Dependency problem on Debian bullseye

### ISSUE THREAD

**Issue by mskwarek** [mkcms/maildirwatch#1]
There is a problem with dependencies on Debian 5.4.19-1 (2020-02-13) x86_64:
```console
$ maildirwatch
Traceback (most recent call last):
  File "/home/marcin/.local/bin/maildirwatch", line 5, in <module>
    from maildirwatch import main
  File "/home/marcin/.local/lib/python3.8/site-packages/maildirwatch.py", line 122, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
```

I've installed mentioned package `libgirepository1.0-dev` but it's not enough. Application requires also `gir1.2-notify-0.7`.

**Comment by mkcms** [comment]
Thanks, I mentioned this in README
